#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
stacks=[]
count,result=0,0
while n>0:
    rem=n%2
    stacks.append(rem)
    n=n//2
    
for i in range(0,len(stacks)):
    if stacks[i]==0:
        count=0
    else:
        count+=1
        result=max(count,result)
print(result)
    
